# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WatchAndSee' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'
  pod 'Firebase/Core'
  pod 'Firebase/Database'

end

target 'WatchAndSeeTests' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'
  pod 'Firebase/Core'
  pod 'Firebase/Database'


end
